### ISSUE TITLE
Does also passing 'state' makes sense?

### ISSUE THREAD

**Issue by kaisermann** [tivac/svelte-routing#1]
I wasn't familiar with `page` and loved your adaptation with svelte. I'm wondering if passing the `ctx.state` property to the components makes sense 🤔 

```js
const handler = (component, data = {}) => (
  { components, params, state: { path, ...state } },
  next,
) => {
  components.push({
    component,
    data: Object.assign(data, params, state),
  });

  return next();
};
```

This way I'm able to call pages with a data object like: 

`page('/foo', { bar: 'test' })`

**Comment by tivac** [comment]
Sure! Pass whatever you want, really. We weren't using that feature so didn't include it in this spike.
